"""Reading text out of real documents, including the ones designed to be difficult.

Runs against files generated by `scripts/make_fixtures.py` rather than against bytes
assembled inline. A hand-built `b"%PDF-1.7 ..."` proves the magic-byte check and nothing
else — every finding in this file came from a document a parser actually had to open.
"""

import pytest

from app.evidence import extraction
from tests.evidence.conftest import fixture_bytes as _read

# --- the ordinary case ---------------------------------------------------------------


@pytest.mark.parametrize(
    "name",
    [
        "immigration-status.pdf",
        "english-test.pdf",
        "life-in-the-uk.pdf",
        "travel-booking.pdf",
    ],
)
def test_a_supported_document_yields_its_text(name: str) -> None:
    found = extraction.extract(_read(name))

    assert found.page_count == 1
    assert found.has_text_layer
    assert "Amara Okonkwo" in found.content
    assert not found.truncated


def test_the_text_is_read_rather_than_inferred() -> None:
    """The line M7 is built on. Nothing here proposes anything — the content is what the
    document says, so there is no claim to confirm and no model to distrust."""
    found = extraction.extract(_read("travel-booking.pdf"))

    assert "SYNTH-TRV-000004" in found.content
    assert "5 June 2024" in found.content


# --- the awkward ones ----------------------------------------------------------------


def test_a_scan_with_no_text_layer_is_a_finding_not_a_failure() -> None:
    """A photograph of a page is a valid, readable document that says nothing to a text
    parser. Failing it would tell the user to fix a file that is perfectly fine; reading
    it needs OCR or a multimodal model, both M8."""
    found = extraction.extract(_read("scan-no-text-layer.pdf"))

    assert found.page_count == 1
    assert found.character_count == 0
    assert not found.has_text_layer


def test_a_password_protected_document_is_refused_before_any_page_is_touched() -> None:
    """Terminal — no retry produces a password. Checked on `needs_pass` rather than by
    trying to read a page, because an encrypted page object is not readable anyway and
    asking turns a clean answer into a parser error."""
    with pytest.raises(extraction.PasswordProtected):
        extraction.extract(_read("password-protected.pdf"))


def test_a_file_that_is_not_a_pdf_is_unreadable_rather_than_a_crash() -> None:
    """A C parser given attacker-controlled input must not raise a `RuntimeError` into
    the task. It becomes a failure code, which becomes a state a user can act on."""
    with pytest.raises(extraction.UnreadableDocument):
        extraction.extract(_read("not-really-a-pdf.pdf"))


def test_an_empty_file_is_unreadable() -> None:
    with pytest.raises(extraction.UnreadableDocument):
        extraction.extract(_read("empty.pdf"))


def test_a_long_document_is_truncated_rather_than_abandoned() -> None:
    """A bounded read of a long document is worth more than no read at all — and
    `truncated` is what stops a downstream consumer mistaking page 40 of 60 for the
    whole thing."""
    found = extraction.extract(_read("many-pages.pdf"))

    assert found.page_count == 60, "the real page count is reported, not the capped one"
    assert found.truncated
    assert found.has_text_layer
    # Read up to the cap, and no further.
    assert "Page 1 of 60" in found.content
    assert f"Page {extraction.MAX_PAGES} of 60" in found.content
    assert f"Page {extraction.MAX_PAGES + 1} of 60" not in found.content


def test_a_document_that_expands_enormously_is_still_bounded() -> None:
    """A 50KB file that decodes to 48MB. A page cap cannot help — this expands on open or
    on one page, before there is anything to count — so what is asserted here is that the
    *read* stays bounded. The container-level control (worker recycling, `mem_limit`) is
    what handles the rest, and cannot be asserted from inside the process it protects."""
    found = extraction.extract(_read("huge-embedded-image.pdf"))

    assert found.page_count == 1
    assert found.character_count <= extraction.MAX_CHARACTERS


def test_the_character_cap_holds_even_when_the_page_cap_does_not(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Two independent bounds. A document inside the page limit can still be a page that
    expands to a gigabyte of text, so the character cap is not redundant with it."""
    monkeypatch.setattr(extraction, "MAX_CHARACTERS", 50)

    found = extraction.extract(_read("many-pages.pdf"))

    assert found.character_count <= 50
    assert found.truncated


def test_a_multi_page_scan_is_not_reported_as_read() -> None:
    """The defect a single-page fixture could not find.

    `"\\n".join` over N empty pages gives a string of length N-1, so counting the joined
    string reported a three-page scan as having two characters — `has_text_layer` became
    True, the run SUCCEEDED, and the user was shown "Read — the text has been read" about
    a document from which nothing was read. Directive 7, inverted, on the screen whose
    entire job is to say what the system has and has not done.
    """
    found = extraction.extract(_read("scan-multi-page.pdf"))

    assert found.page_count == 3
    assert found.pages_read == 3
    assert found.character_count == 0
    assert not found.has_text_layer


def test_a_page_of_only_whitespace_counts_as_no_text() -> None:
    """A page containing a space is a page with nothing on it. Counting it as text would
    reintroduce the same false reassurance by a narrower route."""
    import io

    import pymupdf

    doc = pymupdf.open()
    page = doc.new_page()
    page.insert_text((72, 100), "   ")
    buffer = io.BytesIO()
    doc.save(buffer)
    doc.close()

    found = extraction.extract(buffer.getvalue())
    assert not found.has_text_layer


def test_pages_read_is_reported_separately_from_the_page_count() -> None:
    """They are not interchangeable, and a consumer that assumes they are describes a
    partial reading as a complete one."""
    found = extraction.extract(_read("many-pages.pdf"))

    assert found.page_count == 60
    assert found.pages_read == extraction.MAX_PAGES
    assert found.pages_read < found.page_count


def test_a_document_that_tries_to_give_instructions_is_read_as_inert_text() -> None:
    """Directive 8: uploaded documents are data, never instructions.

    No model reads this in M7 — there is none — so the assertion available today is that
    extraction treats an injection payload exactly like any other text: returned, with no
    branch anywhere that notices what it says. That is the correct behaviour and worth
    pinning *now*, because this function is what will hand text to a model in M8, and the
    property to preserve is that this layer never interprets.
    """
    found = extraction.extract(_read("prompt-injection.pdf"))

    assert found.has_text_layer
    # Returned verbatim: not stripped, not flagged, not acted on.
    assert "IGNORE ALL PREVIOUS INSTRUCTIONS" in found.content
    assert "</system>" in found.content
    # And it is text like any other — the counts treat it no differently.
    assert found.character_count == len(found.content)


def test_a_pdf_with_no_pages_is_corrupt_rather_than_a_scan() -> None:
    """A truncated or structurally broken file opens and reports zero pages. Landing that
    on the zero-length reading path would call it a scan — telling the user their
    perfectly good photograph could not be read, when what they have is a damaged file."""
    with pytest.raises(extraction.UnreadableDocument):
        extraction.extract(b"%PDF-1.4\n1 0 obj\n<< /Type /Catalog >>\nendobj\ntrailer\n<< >>\n")


def test_the_read_gives_up_at_its_deadline(monkeypatch: pytest.MonkeyPatch) -> None:
    """The bound that was missing, and the one that matters.

    A page cap bounds how much text comes *out*, not how much work it costs to get — a
    single-page PDF nesting Form XObjects costs exponential time inside one `get_text()`
    call while producing two characters, at around 6 KB. The deadline is what stops a
    multi-page version of that holding a worker slot for as long as the uploader likes.
    """
    monkeypatch.setattr(extraction, "DEADLINE_SECONDS", -1.0)

    found = extraction.extract(_read("many-pages.pdf"))

    assert found.pages_read == 0, "the deadline was already past, so nothing was read"
    assert found.truncated, "a bounded read must say it was bounded"
    assert found.page_count == 60, "the document's own page count is still reported"


def test_the_task_deadline_is_never_reported_as_a_corrupt_document(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """`SoftTimeLimitExceeded` derives from `Exception`, so the broad parser-failure
    handlers caught Celery's own deadline and reported the file as corrupt — telling the
    user a false thing about their document, and letting the task carry on writing past
    the moment it was told to stop. It has to pass through."""
    from celery.exceptions import SoftTimeLimitExceeded

    def stop(*_args: object, **_kwargs: object) -> None:
        raise SoftTimeLimitExceeded()

    # Patched by name on the module under test rather than through its import, so the
    # patch cannot reach any other user of PyMuPDF in the process.
    monkeypatch.setattr("app.evidence.extraction.pymupdf.open", stop)

    with pytest.raises(SoftTimeLimitExceeded):
        extraction.extract(_read("travel-booking.pdf"))
