"""Reading text out of real documents, including the ones designed to be difficult.

Runs against files generated by `scripts/make_fixtures.py` rather than against bytes
assembled inline. A hand-built `b"%PDF-1.7 ..."` proves the magic-byte check and nothing
else — every finding in this file came from a document a parser actually had to open.
"""

import pytest

from app.evidence import extraction
from tests.evidence.conftest import fixture_bytes as _read

# --- the ordinary case ---------------------------------------------------------------


@pytest.mark.parametrize(
    "name",
    [
        "immigration-status.pdf",
        "english-test.pdf",
        "life-in-the-uk.pdf",
        "travel-booking.pdf",
    ],
)
def test_a_supported_document_yields_its_text(name: str) -> None:
    found = extraction.extract(_read(name))

    assert found.page_count == 1
    assert found.has_text_layer
    assert "Amara Okonkwo" in found.content
    assert not found.truncated


def test_the_text_is_read_rather_than_inferred() -> None:
    """The line M7 is built on. Nothing here proposes anything — the content is what the
    document says, so there is no claim to confirm and no model to distrust."""
    found = extraction.extract(_read("travel-booking.pdf"))

    assert "SYNTH-TRV-000004" in found.content
    assert "5 June 2024" in found.content


# --- the awkward ones ----------------------------------------------------------------


def test_a_scan_with_no_text_layer_is_a_finding_not_a_failure() -> None:
    """A photograph of a page is a valid, readable document that says nothing to a text
    parser. Failing it would tell the user to fix a file that is perfectly fine; reading
    it needs OCR or a multimodal model, both M8."""
    found = extraction.extract(_read("scan-no-text-layer.pdf"))

    assert found.page_count == 1
    assert found.character_count == 0
    assert not found.has_text_layer


def test_a_password_protected_document_is_refused_before_any_page_is_touched() -> None:
    """Terminal — no retry produces a password. Checked on `needs_pass` rather than by
    trying to read a page, because an encrypted page object is not readable anyway and
    asking turns a clean answer into a parser error."""
    with pytest.raises(extraction.PasswordProtected):
        extraction.extract(_read("password-protected.pdf"))


def test_a_file_that_is_not_a_pdf_is_unreadable_rather_than_a_crash() -> None:
    """A C parser given attacker-controlled input must not raise a `RuntimeError` into
    the task. It becomes a failure code, which becomes a state a user can act on."""
    with pytest.raises(extraction.UnreadableDocument):
        extraction.extract(_read("not-really-a-pdf.pdf"))


def test_an_empty_file_is_unreadable() -> None:
    with pytest.raises(extraction.UnreadableDocument):
        extraction.extract(_read("empty.pdf"))


def test_a_long_document_is_truncated_rather_than_abandoned() -> None:
    """A bounded read of a long document is worth more than no read at all — and
    `truncated` is what stops a downstream consumer mistaking page 40 of 60 for the
    whole thing."""
    found = extraction.extract(_read("many-pages.pdf"))

    assert found.page_count == 60, "the real page count is reported, not the capped one"
    assert found.truncated
    assert found.has_text_layer
    # Read up to the cap, and no further.
    assert "Page 1 of 60" in found.content
    assert f"Page {extraction.MAX_PAGES} of 60" in found.content
    assert f"Page {extraction.MAX_PAGES + 1} of 60" not in found.content


def test_a_document_that_expands_enormously_is_still_bounded() -> None:
    """A 50KB file that decodes to 48MB. A page cap cannot help — this expands on open or
    on one page, before there is anything to count — so what is asserted here is that the
    *read* stays bounded. The container-level control (worker recycling, `mem_limit`) is
    what handles the rest, and cannot be asserted from inside the process it protects."""
    found = extraction.extract(_read("huge-embedded-image.pdf"))

    assert found.page_count == 1
    assert found.character_count <= extraction.MAX_CHARACTERS


def test_the_character_cap_holds_even_when_the_page_cap_does_not(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Two independent bounds. A document inside the page limit can still be a page that
    expands to a gigabyte of text, so the character cap is not redundant with it."""
    monkeypatch.setattr(extraction, "MAX_CHARACTERS", 50)

    found = extraction.extract(_read("many-pages.pdf"))

    assert found.character_count <= 50
    assert found.truncated
